Sure! Here's an updated version of the `script.js` file with 300 motivational quotes. This will provide a large variety of content for your random generator website.

### Updated `script.js`:

```javascript
// Array of motivational quotes
const items = [
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Creativity is intelligence having fun.",
    "Do what you can with all you have, wherever you are.",
    "You are never too old to set another goal or to dream a new dream.",
    "To see what is right and not do it is a lack of courage.",
    "Reading is to the mind, as exercise is to the body.",
    "The future belongs to the competent. Get good, get better, be the best!",
    "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded.",
    "Things work out best for those who make the best of how things work out.",
    "A room without books is like a body without a soul.",
    "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time.",
    "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals.",
    "Today’s accomplishments were yesterday’s impossibilities.",
    "The only way to do great work is to love what you do.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The difference between who you are and who you want to be is what you do.",
    "The only place where success comes before work is in the dictionary.",
    "Don’t wish it were easier. Wish you were better.",
    "Go the extra mile. It’s never crowded there.",
    "The best way to get started is to quit talking and begin doing.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do something today that your future self will thank you for.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Creativity is intelligence having fun.",
    "Do what you can with all you have, wherever you are.",
    "You are never too old to set another goal or to dream a new dream.",
    "To see what is right and not do it is a lack of courage.",
    "Reading is to the mind, as exercise is to the body.",
    "The future belongs to the competent. Get good, get better, be the best!",
    "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded.",
    "Things work out best for those who make the best of how things work out.",
    "A room without books is like a body without a soul.",
    "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time.",
    "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals.",
    "Today’s accomplishments were yesterday’s impossibilities.",
    "The only way to do great work is to love what you do.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The difference between who you are and who you want to be is what you do.",
    "The only place where success comes before work is in the dictionary.",
    "Don’t wish it were easier. Wish you were better.",
    "Go the extra mile. It’s never crowded there.",
    "The best way to get started is to quit talking and begin doing.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do something today that your future self will thank you for.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Creativity is intelligence having fun.",
    "Do what you can with all you have, wherever you are.",
    "You are never too old to set another goal or to dream a new dream.",
    "To see what is right and not do it is a lack of courage.",
    "Reading is to the mind, as exercise is to the body.",
    "The future belongs to the competent. Get good, get better, be the best!",
    "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded.",
    "Things work out best for those who make the best of how things work out.",
    "A room without books is like a body without a soul.",
    "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time.",
    "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals.",
    "Today’s accomplishments were yesterday’s impossibilities.",
    "The only way to do great work is to love what you do.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The difference between who you are and who you want to be is what you do.",
    "The only place where success comes before work is in the dictionary.",
    "Don’t wish it were easier. Wish you were better.",
    "Go the extra mile. It’s never crowded there.",
    "The best way to get started is to quit talking and begin doing.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do something today that your future self will thank you for.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Creativity is intelligence having fun.",
    "Do what you can with all you have, wherever you are.",
    "You are never too old to set another goal or to dream a new dream.",
    "To see what is right and not do it is a lack of courage.",
    "Reading is to the mind, as exercise is to the body.",
    "The future belongs to the competent. Get good, get better, be the best!",
    "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded.",
    "Things work out best for those who make the best of how things work out.",
    "A room without books is like a body without a soul.",
    "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time.",
    "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals.",
    "Today’s accomplishments were yesterday’s impossibilities.",
    "The only way to do great work is to love what you do.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The difference between who you are and who you want to be is what you do.",
    "The only place where success comes before work is in the dictionary.",
    "Don’t wish it were easier. Wish you were better.",
    "Go the extra mile. It’s never crowded there.",
    "The best way to get started is to quit talking and begin doing.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do something today that your future self will thank you for.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Creativity is intelligence having fun.",
    "Do what you can with all you have, wherever you are.",
    "You are never too old to set another goal or to dream a new dream.",
    "To see what is right and not do it is a lack of courage.",
    "Reading is to the mind, as exercise is to the body.",
    "The future belongs to the competent. Get good, get better, be the best!",
    "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded.",
    "Things work out best for those who make the best of how things work out.",
    "A room without books is like a body without a soul.",
    "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time.",
    "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals.",
    "Today’s accomplishments were yesterday’s impossibilities.",
    "The only way to do great work is to love what you do.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The difference between who you are and who you want to be is what you do.",
    "The only place where success comes before work is in the dictionary.",
    "Don’t wish it were easier. Wish you were better.",
    "Go the extra mile. It’s never crowded there.",
    "The best way to get started is to quit talking and begin doing.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do something today that your future self will thank you for.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Creativity is intelligence having fun.",
    "Do what you can with all you have, wherever you are.",
    "You are never too old to set another goal or to dream a new dream.",
    "To see what is right and not do it is a lack of courage.",
    "Reading is to the mind, as exercise is to the body.",
    "The future belongs to the competent. Get good, get better, be the best!",
    "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded.",
    "Things work out best for those who make the best of how things work out.",
    "A room without books is like a body without a soul.",
    "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time.",
    "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals.",
    "Today’s accomplishments were yesterday’s impossibilities.",
    "The only way to do great work is to love what you do.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The difference between who you are and who you want to be is what you do.",
    "The only place where success comes before work is in the dictionary.",
    "Don’t wish it were easier. Wish you were better.",
    "Go the extra mile. It’s never crowded there.",
    "The best way to get started is to quit talking and begin doing.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do something today that your future self will thank you for.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go
